"""Production company catalog — 20 top tech employers."""

COMPANIES = [
    {
        "name": "Google",
        "slug": "google",
        "logo": "https://www.google.com/s2/favicons?domain=google.com&sz=128",
        "description": "Search, cloud, Android, and cutting-edge AI research.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["FAANG", "AI", "Scale"],
        "interview_count": 4,
        "estimated_salary": "$180K – $350K",
        "preparation_time": "8–12 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 98,
    },
    {
        "name": "Amazon",
        "slug": "amazon",
        "logo": "https://www.google.com/s2/favicons?domain=amazon.com&sz=128",
        "description": "E-commerce, AWS, and leadership principles-driven interviews.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["FAANG", "AWS", "Leadership"],
        "interview_count": 5,
        "estimated_salary": "$160K – $320K",
        "preparation_time": "6–10 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 97,
    },
    {
        "name": "Microsoft",
        "slug": "microsoft",
        "logo": "https://www.google.com/s2/favicons?domain=microsoft.com&sz=128",
        "description": "Azure, Office 365, and enterprise software engineering.",
        "difficulty": "Medium",
        "category": "Product",
        "trending": True,
        "tags": ["FAANG", "Cloud", "Enterprise"],
        "interview_count": 4,
        "estimated_salary": "$150K – $300K",
        "preparation_time": "6–8 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 96,
    },
    {
        "name": "Apple",
        "slug": "apple",
        "logo": "https://www.google.com/s2/favicons?domain=apple.com&sz=128",
        "description": "Hardware, iOS/macOS, and premium consumer technology.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["FAANG", "iOS", "Design"],
        "interview_count": 4,
        "estimated_salary": "$170K – $340K",
        "preparation_time": "8–10 weeks",
        "hiring_status": "Selective hiring",
        "popularity_score": 95,
    },
    {
        "name": "Meta",
        "slug": "meta",
        "logo": "https://www.google.com/s2/favicons?domain=meta.com&sz=128",
        "description": "Social platforms, VR/AR, and large-scale distributed systems.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["FAANG", "Social", "ML"],
        "interview_count": 4,
        "estimated_salary": "$175K – $360K",
        "preparation_time": "8–12 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 94,
    },
    {
        "name": "Netflix",
        "slug": "netflix",
        "logo": "https://www.google.com/s2/favicons?domain=netflix.com&sz=128",
        "description": "Streaming, recommendations, and high-performance engineering culture.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["Streaming", "Culture", "Scale"],
        "interview_count": 3,
        "estimated_salary": "$200K – $500K",
        "preparation_time": "6–8 weeks",
        "hiring_status": "Selective hiring",
        "popularity_score": 88,
    },
    {
        "name": "Adobe",
        "slug": "adobe",
        "logo": "https://www.google.com/s2/favicons?domain=adobe.com&sz=128",
        "description": "Creative Cloud, digital experience, and document platforms.",
        "difficulty": "Medium",
        "category": "Product",
        "trending": True,
        "tags": ["SaaS", "Creative", "Product"],
        "interview_count": 3,
        "estimated_salary": "$140K – $260K",
        "preparation_time": "4–6 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 82,
    },
    {
        "name": "Uber",
        "slug": "uber",
        "logo": "https://www.google.com/s2/favicons?domain=uber.com&sz=128",
        "description": "Mobility marketplace and real-time logistics at global scale.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["Marketplace", "Real-time", "Mobile"],
        "interview_count": 4,
        "estimated_salary": "$160K – $310K",
        "preparation_time": "6–8 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 85,
    },
    {
        "name": "Flipkart",
        "slug": "flipkart",
        "logo": "https://www.google.com/s2/favicons?domain=flipkart.com&sz=128",
        "description": "India's leading e-commerce and supply-chain technology.",
        "difficulty": "Medium",
        "category": "Product",
        "trending": True,
        "tags": ["E-commerce", "India", "Scale"],
        "interview_count": 4,
        "estimated_salary": "₹25L – ₹60L",
        "preparation_time": "4–8 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 90,
    },
    {
        "name": "Walmart",
        "slug": "walmart",
        "logo": "https://www.google.com/s2/favicons?domain=walmart.com&sz=128",
        "description": "Retail tech, supply chain, and global e-commerce platforms.",
        "difficulty": "Medium",
        "category": "Enterprise",
        "trending": True,
        "tags": ["Retail", "Enterprise", "Scale"],
        "interview_count": 3,
        "estimated_salary": "$130K – $240K",
        "preparation_time": "4–6 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 78,
    },
    {
        "name": "Atlassian",
        "slug": "atlassian",
        "logo": "https://www.google.com/s2/favicons?domain=atlassian.com&sz=128",
        "description": "Jira, Confluence, and collaboration software for teams.",
        "difficulty": "Medium",
        "category": "SaaS",
        "trending": True,
        "tags": ["SaaS", "B2B", "Remote-friendly"],
        "interview_count": 3,
        "estimated_salary": "$140K – $250K",
        "preparation_time": "4–6 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 80,
    },
    {
        "name": "Oracle",
        "slug": "oracle",
        "logo": "https://www.google.com/s2/favicons?domain=oracle.com&sz=128",
        "description": "Databases, cloud infrastructure, and enterprise applications.",
        "difficulty": "Medium",
        "category": "Enterprise",
        "trending": False,
        "tags": ["Database", "Enterprise", "Cloud"],
        "interview_count": 3,
        "estimated_salary": "$120K – $220K",
        "preparation_time": "4–6 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 72,
    },
    {
        "name": "Salesforce",
        "slug": "salesforce",
        "logo": "https://www.google.com/s2/favicons?domain=salesforce.com&sz=128",
        "description": "CRM, cloud SaaS, and enterprise customer platforms.",
        "difficulty": "Medium",
        "category": "SaaS",
        "trending": True,
        "tags": ["CRM", "SaaS", "Enterprise"],
        "interview_count": 3,
        "estimated_salary": "$140K – $280K",
        "preparation_time": "5–7 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 84,
    },
    {
        "name": "Tesla",
        "slug": "tesla",
        "logo": "https://www.google.com/s2/favicons?domain=tesla.com&sz=128",
        "description": "EV software, autonomy, and manufacturing technology.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["Automotive", "Embedded", "AI"],
        "interview_count": 4,
        "estimated_salary": "$150K – $300K",
        "preparation_time": "6–10 weeks",
        "hiring_status": "Selective hiring",
        "popularity_score": 86,
    },
    {
        "name": "Nvidia",
        "slug": "nvidia",
        "logo": "https://www.google.com/s2/favicons?domain=nvidia.com&sz=128",
        "description": "GPUs, AI accelerators, and deep learning infrastructure.",
        "difficulty": "Hard",
        "category": "Hardware",
        "trending": True,
        "tags": ["AI", "GPU", "Systems"],
        "interview_count": 4,
        "estimated_salary": "$180K – $380K",
        "preparation_time": "8–12 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 97,
    },
    {
        "name": "PayPal",
        "slug": "paypal",
        "logo": "https://www.google.com/s2/favicons?domain=paypal.com&sz=128",
        "description": "Payments, fintech security, and global transaction systems.",
        "difficulty": "Medium",
        "category": "Fintech",
        "trending": True,
        "tags": ["Fintech", "Security", "Payments"],
        "interview_count": 3,
        "estimated_salary": "$140K – $260K",
        "preparation_time": "4–6 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 81,
    },
    {
        "name": "Spotify",
        "slug": "spotify",
        "logo": "https://www.google.com/s2/favicons?domain=spotify.com&sz=128",
        "description": "Audio streaming, recommendations, and data-driven product.",
        "difficulty": "Medium",
        "category": "Product",
        "trending": True,
        "tags": ["Streaming", "ML", "Product"],
        "interview_count": 3,
        "estimated_salary": "$130K – $250K",
        "preparation_time": "5–7 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 83,
    },
    {
        "name": "Airbnb",
        "slug": "airbnb",
        "logo": "https://www.google.com/s2/favicons?domain=airbnb.com&sz=128",
        "description": "Marketplace, travel tech, and trust & safety systems.",
        "difficulty": "Hard",
        "category": "Product",
        "trending": True,
        "tags": ["Marketplace", "Product", "Design"],
        "interview_count": 4,
        "estimated_salary": "$160K – $320K",
        "preparation_time": "6–8 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 87,
    },
    {
        "name": "LinkedIn",
        "slug": "linkedin",
        "logo": "https://www.google.com/s2/favicons?domain=linkedin.com&sz=128",
        "description": "Professional network, feed ranking, and B2B data products.",
        "difficulty": "Medium",
        "category": "Product",
        "trending": True,
        "tags": ["Social", "B2B", "Microsoft"],
        "interview_count": 3,
        "estimated_salary": "$150K – $290K",
        "preparation_time": "5–7 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 85,
    },
    {
        "name": "Intel",
        "slug": "intel",
        "logo": "https://www.google.com/s2/favicons?domain=intel.com&sz=128",
        "description": "Semiconductors, chip design, and hardware-software co-design.",
        "difficulty": "Medium",
        "category": "Hardware",
        "trending": False,
        "tags": ["Hardware", "Embedded", "Systems"],
        "interview_count": 3,
        "estimated_salary": "$120K – $220K",
        "preparation_time": "6–8 weeks",
        "hiring_status": "Actively hiring",
        "popularity_score": 74,
    },
]
